title: Heap Exploitation
description: A beginners guide to exploiting the heap
theme: just-the-docs

url: https://hehirm.github.io/heapexploittutorial

aux_links:
  Template Repository: https://github.com/hehirm/heapexploittutorial
